import { z } from 'zod';

export const schemaValuteProperty = z.object({
  ID: z.string(),
  NumCode: z.string(),
  CharCode: z.string(),
  Nominal: z.number(),
  Name: z.string(),
  Value: z.number(),
  Previous: z.number(),
});

export const schemaGetResponse = z.object({
  Date: z.string(),
  PreviousDate: z.string(),
  PreviousURL: z.string(),
  Timestamp: z.string(),
  Valute: z.object({
    AUD: schemaValuteProperty,
    AZN: schemaValuteProperty,
    GBP: schemaValuteProperty,
    AMD: schemaValuteProperty,
    BYN: schemaValuteProperty,
    BGN: schemaValuteProperty,
    BRL: schemaValuteProperty,
    HUF: schemaValuteProperty,
    VND: schemaValuteProperty,
    HKD: schemaValuteProperty,
    GEL: schemaValuteProperty,
    DKK: schemaValuteProperty,
    AED: schemaValuteProperty,
    USD: schemaValuteProperty,
    EUR: schemaValuteProperty,
    EGP: schemaValuteProperty,
    INR: schemaValuteProperty,
    IDR: schemaValuteProperty,
    KZT: schemaValuteProperty,
    CAD: schemaValuteProperty,
    QAR: schemaValuteProperty,
    KGS: schemaValuteProperty,
    CNY: schemaValuteProperty,
    MDL: schemaValuteProperty,
    NZD: schemaValuteProperty,
    NOK: schemaValuteProperty,
    PLN: schemaValuteProperty,
    RON: schemaValuteProperty,
    XDR: schemaValuteProperty,
    SGD: schemaValuteProperty,
    TJS: schemaValuteProperty,
    THB: schemaValuteProperty,
    TRY: schemaValuteProperty,
    TMT: schemaValuteProperty,
    UZS: schemaValuteProperty,
    UAH: schemaValuteProperty,
    CZK: schemaValuteProperty,
    SEK: schemaValuteProperty,
    CHF: schemaValuteProperty,
    RSD: schemaValuteProperty,
    ZAR: schemaValuteProperty,
    KRW: schemaValuteProperty,
    JPY: schemaValuteProperty,
  }),
});
